#!/usr/bin/env sh
#MISE description="Push the gem to gem.coop under @aaron"
#MISE depends=["build"]
#USAGE arg "<push_key>" help="API key for gem.coop"

set -e

# usage_push_key comes from the USAGE arg above, set by mise.
# shellcheck disable=SC2154
GEM_HOST_API_KEY="${usage_push_key}" gem push pkg/phlex-hanami-*.gem --host https://gem.coop/@aaron
