name: Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - "[0-9]+.*"
  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install mise
        uses: jdx/mise-action@v4

      - name: Setup
        run: mise run setup

      - name: Lint
        run: mise run lint

      - name: Test
        run: mise run test
